### PR TITLE
Update workflows to create build as artifact

### PR DESCRIPTION
**Pull request by basharkey**
- Modify QA workflow to build APK and upload as an artifact
- New workflow to create comment linking to artifact files

You can download the artifact using the direct link but it requires OAuth so I would just recommend pulling it from the build log.

Tested here: https://github.com/basharkey/nextcloud-android/pull/3

### CODE REVIEW

**Comment by basharkey** [comment]
Probably going to want to squash this as my commit descriptions are a bit lacking :sweat:

**Comment by Elv1zz** [comment]
Thanks for the PR 👍  I am beginning to understand the issue now... (even though I do know CI and pipelines, I am not a Github expert 😆). So I assume I should not include your commits to my `master` branch, since they should not go to the main nextcloud repo. Therefore I created a new `qa` branch and re-targeted the PR.
But I also just updated my repo to the most recent `master` branch of the nextcloud repo, which requires rebasing my commits to their branch state 😒 This now causes trouble with your commits being based on my un-rebased commits...

So either you have to rebase your repo to my rebased repo, before I can merge your commits... or I simply copy over your changes manually into my `qa` branch, which would lose your authorship of the commits.

It's up to you to decide.

**Comment by basharkey** [comment]
I've honestly never run a rebase before but I think I've done it correctly. It's saying it's mergeable so it looks good to me! Let me know if I've done something wrong here.

**Comment by Elv1zz** [comment]
> Let me know if I've done something wrong here.

No, everything looks fine now, thanks a lot!

So, if I understand the pipeline correctly, it will create and upload a new `qaDebug` APK for every (updated?) PR towards *master* branch, right?
If I want to create an APK, I first have to have a PR from *qa* to *master*. If I later want to update that APK, I commit and push my code changes to *master*, merge that into *qa* and the new APK should get created, right?

**Comment by basharkey** [comment]
You have the first part right. Now that you've merged whenever you create a PR against your `master` branch the action should automatically generate an APK and comment on the PR.

Any time you push further commits to that branch it should regenerate the APK and comment again. So you don't have to merge to `master` to regenerate the APK just simply push your new changes to the branch with an open PR.

**Comment by Elv1zz** [comment]
Thanks for the explanation :) 
I was a bit unclear in my question, because I had my workflow in mind, where I do all the work on `master` (not really ideal, though, but I never expected this PR towards upstream to take that long...). 

Of course Github changed their runner images so the workflow in `qa.yml` broke since the Android tools seem to have been moved. But I was able to fix it. But at least in the previous run, the comment was not added to the PR 🤔  But at leas the artifact was created and uploaded. So let's see if it works in the second run.

**Pull request merged**
